# Generated by Django 5.2.2 on 2025-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(default='Nulo', max_length=50),
            preserve_default=False,
        ),
    ]
